[profile.default]
src = "contracts"
test = "test-foundry"
libs = ["node_modules"]
cache_path = "cache-foundry"
out = "out-foundry"
solc_version = "0.8.30"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 1
via_ir = true
fuzz = { runs = 256 }
invariant = { runs = 128, depth = 64, fail_on_revert = false }
